### ISSUE TITLE
Setting dev envoiriment result in a connection refused

### ISSUE THREAD

**Issue by vincenzopalazzo** [btcpayserver/app#105]
Trying to run the application, but looks like I can not connect to the local btcpay server.

Running the project with `dotnet run --project BTCPayApp.Server/BTCPayApp.Server.csproj`

Then use the Readme to start the server

```
# Go to the server submodule
cd submodules/btcpayserver/BTCPayServer.Tests

# Verify you are on the `mobile-working-branch` branch
git branch --show current

# If not, check it out
git checkout mobile-working-branch

# Run the server
docker-compose up dev
```

Getting the following result
![Selection_229](https://github.com/user-attachments/assets/076075e9-d71a-4322-a94a-ee960f79db62)

**Comment by pavlenex** [comment]
@dennisreimann I believe it's a certificate thing or perhaps @vincenzopalazzo needs to wait for server to deploy which takes a few moments?

**Comment by dennisreimann** [comment]
The important part is this one: 

> Now you can open up the IDE and run DEV ALL profile which builds both the App and the BTCPay Server.

The app and server are two separate services and need to be run alongside. In the case above, the server isn't started I guess.

**Comment by vincenzopalazzo** [comment]
I have the server up and running apparently, there is any curl command that
I can do to verify that it is up and running?

The DEV ALL script is doing what the readme is suggested too right? the
docker command inside the readme is the same that runs the server with the
DEV ALL, right?

**Comment by dennisreimann** [comment]
If you start the server, `https://localhost:14142/` should open automatically — that's also the URL you'd enter into the connect input.

**Comment by vincenzopalazzo** [comment]
> If you start the server, https://localhost:14142/ should open automatically — that's also the URL you'd enter into the connect input.

OK now I tried with a "real" editor, and I noted the following stacktrace

```
warn: BTCPayServer.Hosting.MigrationStartupTask: Error while running migration scripts, retrying...
Npgsql.NpgsqlException (0x80004005): Failed to connect to 127.0.0.1:39372
 ---> System.Net.Sockets.SocketException (111): Connection refused
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at Npgsql.TaskTimeoutAndCancellation.ExecuteAsync(Func`2 getTaskFunc, NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.ConnectAsync(NpgsqlTimeout timeout, CancellationToken cancellationToken)
   at Npgsql.Internal.NpgsqlConnector.RawOpen(SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.<Open>g__OpenCore|213_1(NpgsqlConnector conn, SslMode sslMode, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken, Boolean isFirstAttempt)
   at Npgsql.Internal.NpgsqlConnector.Open(NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.UnpooledDataSource.Get(NpgsqlConnection conn, NpgsqlTimeout timeout, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlConnection.<Open>g__OpenAsync|42_0(Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlDatabaseCreator.Exists(Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.GetAppliedMigrationsAsync(CancellationToken cancellationToken)
   at Npgsql.EntityFrameworkCore.PostgreSQL.Migrations.Internal.NpgsqlMigrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at BTCPayServer.Hosting.MigrationStartupTask.Migrate(CancellationToken cancellationToken) in /home/vincent/github/work/app/submodules/btcpayserver/BTCPayServer/Hosting/MigrationStartupTask.cs:line 920
info: BTCPayServer.Hosting.MigrationStartupTask: Running the migration scripts...

```

May be this related?

**Comment by vincenzopalazzo** [comment]
Thanks @dennisreimann 

Looks like that on linux we need to run also https://github.com/BorisWilhelms/create-dotnet-devcert for generating the certificate

**Comment by dennisreimann** [comment]
I think I created them using the MS flow: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-dev-certs

However, if it works then you're good to go :)

**Comment by vincenzopalazzo** [comment]
>However, if it works then you're good to go :)

Bear with me a little bit rusty with dotnet haha I will keep up with time, thanks for pointing me to the right direction!
