### ISSUE TITLE
Bug - Onchain wallet view `Object reference not set to an instance of an object.`

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#114]
I am unsure what I did, but I just clicked on the view in the settings and noticed this.

![Screenshot 2024-11-25 at 13 22 49](https://github.com/user-attachments/assets/afd82158-b320-4a9b-9c28-6749b7a574c6)

Don't think the logs are related but perhaps they are:

```
ers/p/Downloads/pavlenex/app/BTCPayApp.Server/bin/Debug/net8.0/BTCPayApp.Server
info: BTCPayApp.Core.AppDatabaseMigrator[0]
      Applying 5 migrations
info: BTCPayApp.Core.AppDatabaseMigrator[0]
      Migrations applied: 20240627110659_Init, 20240726135741_triggers, 20240731112534_triggers2, 20240805085647_checkpoitnchannels, 20240820073346_channelpimp
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: WaitingForAuth from Init
info: BTCPayApp.Core.Wallet.LightningNodeManager[0]
      Lightning node state changed: WaitingForConnection from Init
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Wallet state changed: WaitingForConnection from Init
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7016
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5259
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/p/Downloads/pavlenex/app/BTCPayApp.Server
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: Connecting from WaitingForAuth
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerNode: 03bcfe1393b7c2367950defe8f5e28ef220657d8ec0fe5e00c0b2ea6e88fccc087@127.0.0.1:30893
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: Syncing from Connecting
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyNetwork: RegTest
warn: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Existing state found but encryption key is missing, waiting until key is provided
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: WaitingForEncryptionKey from Syncing
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: Syncing from WaitingForEncryptionKey
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 6 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 6 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: ConnectedFinishedInitialSync from Syncing
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: ConnectedAsSlave from ConnectedFinishedInitialSync
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: notifications-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 2 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 2 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: notifications-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 4 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 4 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: notifications-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: notifications-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: notifications-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 4 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 4 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
fail: BTCPayApp.Core.Backup.SyncService[0]
      Error while syncing to local
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at VSS.HttpVSSAPIClient.SendRequestAsync[TRequest,TResponse](TRequest request, Uri url, CancellationToken cancellationToken)
         at VSS.HttpVSSAPIClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken)
         at BTCPayApp.Core.Backup.AccountAwareVssClient.<>c__DisplayClass7_0.<<ListKeyVersionsAsync>b__0>d.MoveNext() in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 56
      --- End of stack trace from previous location ---
         at BTCPayApp.Core.Backup.AccountAwareVssClient.Wrap[T](Func`1 func) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 25
         at BTCPayApp.Core.Backup.AccountAwareVssClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 56
         at VSS.VSSApiEncryptorClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken)
         at BTCPayApp.Core.Backup.SyncService.SyncToLocal(CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 205
         at BTCPayApp.Core.Backup.SyncService.SyncToLocal(CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 291
         at BTCPayApp.Core.Backup.SyncService.ContinuouslySync(Boolean local, CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 443
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: invoice-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: notifications-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 3 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 3 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 2 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 2 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
fail: BTCPayApp.Core.Backup.SyncService[0]
      Error while syncing to local
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at VSS.HttpVSSAPIClient.SendRequestAsync[TRequest,TResponse](TRequest request, Uri url, CancellationToken cancellationToken)
         at VSS.HttpVSSAPIClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken)
         at BTCPayApp.Core.Backup.AccountAwareVssClient.<>c__DisplayClass7_0.<<ListKeyVersionsAsync>b__0>d.MoveNext() in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 56
      --- End of stack trace from previous location ---
         at BTCPayApp.Core.Backup.AccountAwareVssClient.Wrap[T](Func`1 func) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 25
         at BTCPayApp.Core.Backup.AccountAwareVssClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 56
         at VSS.VSSApiEncryptorClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken)
         at BTCPayApp.Core.Backup.SyncService.SyncToLocal(CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 205
         at BTCPayApp.Core.Backup.SyncService.SyncToLocal(CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 291
         at BTCPayApp.Core.Backup.SyncService.ContinuouslySync(Boolean local, CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 443
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to local: 0 to delete, 1 to upsert
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to local: 0 deleted, 1 upserted
fail: BTCPayApp.Core.Backup.SyncService[0]
      Error while syncing to local
      System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
         at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
         at VSS.HttpVSSAPIClient.SendRequestAsync[TRequest,TResponse](TRequest request, Uri url, CancellationToken cancellationToken)
         at VSS.HttpVSSAPIClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken)
         at BTCPayApp.Core.Backup.AccountAwareVssClient.<>c__DisplayClass7_0.<<ListKeyVersionsAsync>b__0>d.MoveNext() in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 56
      --- End of stack trace from previous location ---
         at BTCPayApp.Core.Backup.AccountAwareVssClient.Wrap[T](Func`1 func) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 25
         at BTCPayApp.Core.Backup.AccountAwareVssClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/AccountAwareVssClient.cs:line 56
         at VSS.VSSApiEncryptorClient.ListKeyVersionsAsync(ListKeyVersionsRequest request, CancellationToken cancellationToken)
         at BTCPayApp.Core.Backup.SyncService.SyncToLocal(CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 205
         at BTCPayApp.Core.Backup.SyncService.SyncToLocal(CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 291
         at BTCPayApp.Core.Backup.SyncService.ContinuouslySync(Boolean local, CancellationToken cancellationToken) in /Users/p/Downloads/pavlenex/app/BTCPayApp.Core/Backup/SyncService.cs:line 443
```

**Comment by pavlenex** [comment]
@Kukks perhaps some of the logs are helpful in general, unsrue if they're related to this issue.

**Comment by Kukks** [comment]
logs unrelated, more likely something about the current UI page

**Comment by dennisreimann** [comment]
@pavlenex Can you check if my recent commit fixed this? In that I also removed the destinction between onchain wallet settngs and funds — these are still separate pages, but via Settings you get to the wallet funds page and then you can access the wallet settings from there.

**Comment by pavlenex** [comment]
@dennisreimann I can't replicate this anylonger it seems. But I am getting https://github.com/btcpayserver/app/issues/117 now, unsure if related to fix or not, probably not, we just haven't thought of the use-cases I guess.
