### ISSUE TITLE
BTCPayServer.Payments.Lightning.LightningLikePaymentHandler.GetNodeInfo(LightningPaymentMethodConfig supportedPaymentMethod, PrefixedInvoiceLogs invoiceLogs, Nullable`1 preferOnion, Boolean throws) in 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#123]
It seems there's a probme since submodule has been updated @dennisreimann @Kukks 

Tested on https://github.com/btcpayserver/app/commit/e02f31e5fec429f632f59006c7252c159cdc50cc

```
fail: BTCPayServer.Controllers.BTCPayAppState: Error during node info update
BTCPayServer.Payments.PaymentMethodUnavailableException: Full node not available
   at BTCPayServer.Payments.Lightning.LightningLikePaymentHandler.GetNodeInfo(LightningPaymentMethodConfig supportedPaymentMethod, PrefixedInvoiceLogs invoiceLogs, Nullable`1 preferOnion, Boolean throws) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs:line 145
   at BTCPayServer.Controllers.BTCPayAppState.UpdateNodeInfo() in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/App/BTCPayAppState.cs:line 275
info: Configuration:  Now listening on: https://0.0.0.0:14142
```

Full logs

```
/Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/bin/Debug/net8.0/BTCPayServer
info: Configuration:  Data Directory: /Users/p/.btcpayserver/RegTest
info: Configuration:  Configuration File: /Users/p/.btcpayserver/RegTest/settings.config
info: Configuration:  Creating configuration file
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /Users/p/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Bitcoin - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Altcoins - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPay.App - 2.0.3.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://127.0.0.1:32838/
info: Configuration:  BTC: Cookie file is /Users/p/.nbxplorer/RegTest/.cookie
warn: Configuration:  BTC: Using cookie auth against NBXplorer, but /Users/p/.nbxplorer/RegTest/.cookie is not found
info: Configuration:  Network: Regtest
info: Configuration:  LogFile: /Users/p/.btcpayserver/RegTest/debug.log
info: Configuration:  Log Level: Debug
info: BTCPayServer.Hosting.MigrationStartupTask: Running the migration scripts...
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200225133433_AddApiKeyLabel'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200402065615_AddApiKeyBlob'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200413052418_PlannedTransactions'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200507092343_AddArchivedToInvoice'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200625064111_refundnotificationpullpayments'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200901161733_AddInvoiceEventLogSeverity'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201002145033_AddCreateDateToUser'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201007090617_u2fDeviceCascade'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201015151438_AddDisabledNotificationsToUser'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201108054749_webhooks'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201208054211_invoicesorderindex'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201228225040_AddingInvoiceSearchesTable'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20210314092253_Fido2Credentials'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20211021085011_RemovePayoutDestinationConstraint'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20211125081400_AddUserBlob'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220115184620_AddCustodianAccountData'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220311135252_AddPayoutProcessors'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220414132313_AddLightningAddress'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220518061525_invoice_created_idx'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220523022603_remove_historical_addresses'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220610090843_AddSettingsToStore'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220929132704_label'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20221128062447_jsonb'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230123062447_migrateoldratesource'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230125085242_AddForms'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230130040047_blob2'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230130062447_jsonb2'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230315062447_fixmaxlength'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230504125505_StoreRoles'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230529135505_WebhookDeliveriesCleanup'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230906135844_AddArchivedFlagForStoresAndApps'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231020135844_AddBoltcardsTable'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231121031609_removecurrentrefund'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231219031609_appssettingstojson'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231219031609_translationsmigration'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240104155620_AddApprovalToApplicationUser'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240220000000_FixWalletObjectsWithEmptyWalletId'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240229000000_PayoutAndPullPaymentToJsonBlob'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240229092905_AddManagerAndEmployeeToStoreRoles'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240304003640_addinvoicecolumns'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240317024757_payments_refactor'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240325095923_RemoveCustodian'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240405004015_cleanup_invoice_events'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240501015052_noperiod'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240508015052_fileid'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240726113051_AppStuff'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240826065950_removeinvoicecols'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240827034505_migratepayouts'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240904092905_UpdateStoreOwnerRole'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240913034505_refactorpendinginvoicespayments'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240919085726_refactorinvoiceaddress'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240923065254_refactorpayments'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240924065254_monitoredinvoices'.
info: BTCPayServer.Hosting.MigrationStartupTask: All migration scripts ran successfully
info: Configuration:  Using HTTPS with the default certificate
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: Configuration:  SSH settings detected, testing connection to root@127.0.0.1 on port 21622 ...
info: PayServer:      Checking if any payment arrived on lightning while the server was offline...
info: PayServer:      Processing lightning payments...
info: Configuration:  SSH connection succeeded
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: PayServer:      Starting payment request expiration watcher
info: PayServer:      0 pending payment requests being checked since last run
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Migrating from the beginning
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Migrating from the beginning
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Migration completed
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Post-migration VACUUM (FULL, ANALYZE)
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Migration completed
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Post-migration VACUUM (ANALYZE)
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Post-migration VACUUM (ANALYZE) finished
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Post-migration VACUUM (FULL, ANALYZE) finished
fail: BTCPayServer.Controllers.BTCPayAppState: Error during node info update
BTCPayServer.Payments.PaymentMethodUnavailableException: Full node not available
   at BTCPayServer.Payments.Lightning.LightningLikePaymentHandler.GetNodeInfo(LightningPaymentMethodConfig supportedPaymentMethod, PrefixedInvoiceLogs invoiceLogs, Nullable`1 preferOnion, Boolean throws) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs:line 145
   at BTCPayServer.Controllers.BTCPayAppState.UpdateNodeInfo() in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/App/BTCPayAppState.cs:line 275
info: Configuration:  Now listening on: https://0.0.0.0:14142
```

**Comment by pavlenex** [comment]
I can replicate this pretty reliably on every new deployment. Can't figure out the issue but here are more logs, unsure if anytihng is helpful this time:
```
/Users/p/Downloads/app/BTCPayApp.Server/bin/Debug/net8.0/BTCPayApp.Server
info: BTCPayApp.Core.AppDatabaseMigrator[0]
      Applying 5 migrations
info: BTCPayApp.Core.AppDatabaseMigrator[0]
      Migrations applied: 20240627110659_Init, 20240726135741_triggers, 20240731112534_triggers2, 20240805085647_checkpoitnchannels, 20240820073346_channelpimp
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: WaitingForAuth from Init
info: BTCPayApp.Core.Wallet.LightningNodeManager[0]
      Lightning node state changed: WaitingForConnection from Init
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Wallet state changed: WaitingForConnection from Init
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7016
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5259
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/p/Downloads/app/BTCPayApp.Server
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: Connecting from WaitingForAuth
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerNode: 0348d6f5aeb026b24ea6c1d85042fb0a9ff8094000f51a1efb5a6a3ef19100270a@127.0.0.1:30893
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: Syncing from Connecting
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyNetwork: RegTest
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: ConnectedFinishedInitialSync from Syncing
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      MasterUpdated: -3053246626541522132
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: ConnectedAsMaster from ConnectedFinishedInitialSync
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Wallet state changed: NotConfigured from WaitingForConnection
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Getting best block
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: ConnectedFinishedInitialSync from ConnectedAsMaster
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Wallet state changed: WaitingForConnection from NotConfigured
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: ConnectedAsMaster from ConnectedFinishedInitialSync
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Wallet state changed: NotConfigured from WaitingForConnection
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      Connection state changed: ConnectedFinishedInitialSync from ConnectedAsMaster
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Wallet state changed: WaitingForConnection from NotConfigured
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Got best block
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Generating wallet
info: BTCPayApp.Core.Wallet.OnChainWalletManager[0]
      Wallet state changed: Loaded from WaitingForConnection
info: BTCPayApp.Core.Wallet.LightningNodeManager[0]
      Lightning node state changed: Loading from WaitingForConnection
info: BTCPayApp.Core.Wallet.LightningNodeManager[0]
      Lightning node state changed: WaitingForConnection from Loading
info: BTCPayApp.Core.Backup.SyncService[0]
      Syncing to remote 1 outbox items
info: BTCPayApp.Core.Backup.SyncService[0]
      Synced to remote 1 items and deleted 0 itemsSetting_walletconfig 0
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: user-store-added - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: store-created - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: user-store-added - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: store-updated - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: app-created - BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayAppServerClient[0]
      NotifyServerEvent: BTCPayServer.Client.App.ServerEvent
info: BTCPayApp.Core.BTCPayServer.BTCPayConnectionManager[0]
      OnNotifyServerEvent: store-updated - BTCPayServer.Client.App.ServerEvent
```

Server:

```
info: Configuration:  Data Directory: /Users/p/.btcpayserver/RegTest
info: Configuration:  Configuration File: /Users/p/.btcpayserver/RegTest/settings.config
info: Configuration:  Creating configuration file
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /Users/p/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Bitcoin - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Altcoins - 2.0.3.0
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPay.App - 2.0.3.0
info: Configuration:  Supported chains: BTC
info: Configuration:  BTC: Explorer url is http://127.0.0.1:32838/
info: Configuration:  BTC: Cookie file is /Users/p/.nbxplorer/RegTest/.cookie
warn: Configuration:  BTC: Using cookie auth against NBXplorer, but /Users/p/.nbxplorer/RegTest/.cookie is not found
info: Configuration:  Network: Regtest
info: Configuration:  LogFile: /Users/p/.btcpayserver/RegTest/debug.log
info: Configuration:  Log Level: Debug
info: BTCPayServer.Hosting.MigrationStartupTask: Running the migration scripts...
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200225133433_AddApiKeyLabel'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200402065615_AddApiKeyBlob'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200413052418_PlannedTransactions'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200507092343_AddArchivedToInvoice'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200625064111_refundnotificationpullpayments'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20200901161733_AddInvoiceEventLogSeverity'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201002145033_AddCreateDateToUser'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201007090617_u2fDeviceCascade'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201015151438_AddDisabledNotificationsToUser'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201108054749_webhooks'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201208054211_invoicesorderindex'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20201228225040_AddingInvoiceSearchesTable'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20210314092253_Fido2Credentials'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20211021085011_RemovePayoutDestinationConstraint'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20211125081400_AddUserBlob'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220115184620_AddCustodianAccountData'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220311135252_AddPayoutProcessors'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220414132313_AddLightningAddress'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220518061525_invoice_created_idx'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220523022603_remove_historical_addresses'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220610090843_AddSettingsToStore'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20220929132704_label'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20221128062447_jsonb'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230123062447_migrateoldratesource'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230125085242_AddForms'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230130040047_blob2'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230130062447_jsonb2'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230315062447_fixmaxlength'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230504125505_StoreRoles'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230529135505_WebhookDeliveriesCleanup'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20230906135844_AddArchivedFlagForStoresAndApps'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231020135844_AddBoltcardsTable'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231121031609_removecurrentrefund'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231219031609_appssettingstojson'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20231219031609_translationsmigration'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240104155620_AddApprovalToApplicationUser'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240220000000_FixWalletObjectsWithEmptyWalletId'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240229000000_PayoutAndPullPaymentToJsonBlob'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240229092905_AddManagerAndEmployeeToStoreRoles'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240304003640_addinvoicecolumns'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240317024757_payments_refactor'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240325095923_RemoveCustodian'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240405004015_cleanup_invoice_events'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240501015052_noperiod'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240508015052_fileid'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240726113051_AppStuff'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240826065950_removeinvoicecols'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240827034505_migratepayouts'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240904092905_UpdateStoreOwnerRole'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240913034505_refactorpendinginvoicespayments'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240919085726_refactorinvoiceaddress'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240923065254_refactorpayments'.
info: Microsoft.EntityFrameworkCore.Migrations: Applying migration '20240924065254_monitoredinvoices'.
    : BTCPayServer.Hosting.MigrationStartupTask: All migration scripts ran successfully
info: Configuration:  Using HTTPS with the default certificate
info: Configuration:  Root Path: /
info: Configuration:  Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: Configuration:  SSH settings detected, testing connection to root@127.0.0.1 on port 21622 ...
info: PayServer:      Checking if any payment arrived on lightning while the server was offline...
info: PayServer:      Processing lightning payments...
info: PayServer:      Starting listening NBXplorer (BTC)
info: PayServer:      Start watching invoices
info: Configuration:  SSH connection succeeded
info: PayServer:      Starting payment request expiration watcher
info: PayServer:      0 pending payment requests being checked since last run
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Migrating from the beginning
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Migrating from the beginning
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Migration completed
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Post-migration VACUUM (FULL, ANALYZE)
info: BTCPayServer.HostedServices.PaymentRequestsMigratorHostedService: Post-migration VACUUM (FULL, ANALYZE) finished
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Migration completed
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Post-migration VACUUM (ANALYZE)
info: BTCPayServer.HostedServices.InvoiceBlobMigratorHostedService: Post-migration VACUUM (ANALYZE) finished
info: PayServer:      BTC: Checking if any pending invoice got paid while offline...
info: PayServer:      BTC: 0 payments happened while offline
info: PayServer:      Connected to WebSocket of NBXplorer (BTC)
info: Configuration:  Now listening on: https://0.0.0.0:14142
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery: An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {d1968828-af34-487a-965b-ce3464bfede3} was not found in the key ring. For more information go to https://aka.ms/aspnet/dataprotectionwarning
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
info: PayServer:      New admin admin@test.com registered
info: PayServer:      User admin@test.com logged in
info: PayServer:      New user user@test.com invited by admin@test.com
info: PayServer:      User user@test.com accepted the invite
info: PayServer:      User user@test.com logged in
info: BTCPayServer.Controllers.BTCPayAppState: DeviceMasterSignal called with device identifier -3053246626541522132
info: BTCPayServer.Controllers.BTCPayAppState: DeviceMasterSignal called with active state
info: BTCPayServer.Controllers.BTCPayAppState: DeviceMasterSignal called with same active state
info: BTCPayServer.Controllers.BTCPayAppHub: Getting best block
info: BTCPayServer.Controllers.BTCPayAppHub: Getting best block done
info: BTCPayServer.Controllers.BTCPayAppState: DeviceMasterSignal called with same active state
info: BTCPayServer.App.API.VSSController: VSS backup request processed: encryptionKeyTest
info: BTCPayServer.App.API.VSSController: VSS backup request processed: Setting_walletconfig
```

**Comment by pavlenex** [comment]
Can't replicate this one any longer.
