### ISSUE TITLE
Unhandled exception when setting up lightnign as a store default payment method on the server

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#45]
```
[2024-06-19T10:59:20.154Z] Error: BTCPayServer.Client.GreenfieldValidationException: ConnectionString: Invalid connection string

   at BTCPayServer.Client.BTCPayServerClient.HandleResponse(HttpResponseMessage message) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer.Client/BTCPayServerClient.cs:line 56
   at BTCPayServer.Client.BTCPayServerClient.HandleResponse[T](HttpResponseMessage message) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer.Client/BTCPayServerClient.cs:line 75
   at BTCPayApp.Core.BTCPayAppClient.HandleResponse[T](HttpResponseMessage res) in /Users/p/Downloads/app/BTCPayApp.Core/BTCPayAppClient.cs:line 95
   at BTCPayServer.Client.BTCPayServerClient.UpdateStorePaymentMethod(String storeId, String paymentMethodId, UpdatePaymentMethodRequest request, CancellationToken token) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer.Client/BTCPayServerClient.StorePaymentMethods.cs:line 21
   at BTCPayApp.UI.Pages.Lightning.SetupPage.SetStoreLNWallet() in /Users/p/Downloads/app/BTCPayApp.UI/Pages/Lightning/SetupPage.razor:line 134
   at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
```

**Comment by pavlenex** [comment]
I cannot replicate this anymore.
