### ISSUE TITLE
Getting `Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'storeData' with type 'BTCPayServer.Data.StoreData'. Path 'arguments[0].event.store.userStores[0]'.` when setting wallet as a default store paymenet method

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#64]
```
info: Configuration:  Now listening on: https://0.0.0.0:14142
info: BTCPayServer.Controllers.BTCPayAppHub: Getting best block
info: BTCPayServer.Controllers.BTCPayAppHub: Getting best block done
info: BTCPayServer.Controllers.BTCPayAppHub: Getting fee rate for 20
info: BTCPayServer.Controllers.BTCPayAppHub: Getting fee rate for 20 done
info: BTCPayServer.Controllers.BTCPayAppHub: Getting fee rate for 6
info: BTCPayServer.Controllers.BTCPayAppHub: Getting fee rate for 6 done
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext: Failed writing message. Aborting connection.
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'storeData' with type 'BTCPayServer.Data.StoreData'. Path 'arguments[0].event.store.userStores[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteArguments(Object[] arguments, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteInvocationMessage(InvocationMessage message, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage message, CancellationToken cancellationToken)
fail: Microsoft.AspNetCore.SignalR.HubConnectionContext: Failed writing message. Aborting connection.
Newtonsoft.Json.JsonSerializationException: Self referencing loop detected for property 'storeData' with type 'BTCPayServer.Data.StoreData'. Path 'arguments[0].event.store.userStores[0]'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(JsonWriter writer, Object value, JsonProperty property, JsonContract contract, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteArguments(Object[] arguments, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteInvocationMessage(InvocationMessage message, JsonTextWriter writer)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteMessageCore(HubMessage message, IBufferWriter`1 stream)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.WriteMessage(HubMessage message, IBufferWriter`1 output)
   at Microsoft.AspNetCore.SignalR.Protocol.HubProtocolExtensions.GetMessageBytes(IHubProtocol hubProtocol, HubMessage message)
   at Microsoft.AspNetCore.SignalR.Protocol.NewtonsoftJsonHubProtocol.GetMessageBytes(HubMessage message)
   at Microsoft.AspNetCore.SignalR.SerializedHubMessage.GetSerializedMessage(IHubProtocol protocol)
   at Microsoft.AspNetCore.SignalR.HubConnectionContext.WriteCore(SerializedHubMessage message, CancellationToken cancellationToken)

```

Also getting this on the keypad

```
07/08/2024 06:36:02:Error BTC-LN: Unexpected exception (System.FormatException: The group group:kynngwk6kuvmy2knxe is not connected
at BTCPayServer.Lightning.LightningClientFactory.Create(String connectionString)
at BTCPayServer.Services.LightningClientFactoryService.Create(String lightningConnectionString, BTCPayNetwork network) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/Services/LightningClientFactoryService.cs:line 46
at BTCPayServer.Payments.Lightning.LightningExtensions.CreateLightningClient(LightningPaymentMethodConfig supportedPaymentMethod, BTCPayNetwork network, LightningNetworkOptions options, LightningClientFactoryService lightningClientFactory) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/Payments/Lightning/LightningExtensions.cs:line 19
at BTCPayServer.Payments.Lightning.LightningLikePaymentHandler.ConfigurePrompt(PaymentMethodContext context) in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs:line 101
at BTCPayServer.Payments.PaymentMethodContext.CreatePaymentPrompt() in /Users/p/Downloads/app/submodules/btcpayserver/BTCPayServer/Payments/IPaymentMethodHandler.cs:line 338)
07/08/2024 06:36:02:Info BTC-LN: Payment method details creation took 13 milliseconds
07/08/2024 06:36:02:Error BTC-CHAIN: Payment method unavailable (Amount below the dust threshold. For amounts of this size, it is recommended to enable an off-chain (Lightning) payment method)
07/08/2024 06:36:02:Info BTC-CHAIN: Payment method details creation took 19 milliseconds
```

Thoughts @dennisreimann ?

**Comment by pavlenex** [comment]
Actually this seems to be more relevant 

```
fail: BTCPayApp.UI.Pages.Settings.IndexPage[0]
      Error getting store payment method
      BTCPayServer.Client.GreenfieldAPIException: The payment method is not found
         at BTCPayServer.Client.BTCPayServerClient.HandleResponse(HttpResponseMessage message) in /Users/p/Downloads/Untitled/submodules/btcpayserver/BTCPayServer.Client/BTCPayServerClient.cs:line 67
         at BTCPayServer.Client.BTCPayServerClient.HandleResponse[T](HttpResponseMessage message) in /Users/p/Downloads/Untitled/submodules/btcpayserver/BTCPayServer.Client/BTCPayServerClient.cs:line 75
         at BTCPayApp.Core.BTCPayAppClient.HandleResponse[T](HttpResponseMessage res) in /Users/p/Downloads/Untitled/BTCPayApp.Core/BTCPayAppClient.cs:line 96
         at BTCPayServer.Client.BTCPayServerClient.SendHttpRequest[T](String path, Dictionary`2 queryPayload, HttpMethod method, CancellationToken cancellationToken) in /Users/p/Downloads/Untitled/submodules/btcpayserver/BTCPayServer.Client/BTCPayServerClient.cs:line 93
         at BTCPayServer.Client.BTCPayServerClient.GetStorePaymentMethod(String storeId, String paymentMethodId, Nullable`1 includeConfig, CancellationToken token) in /Users/p/Downloads/Untitled/submodules/btcpayserver/BTCPayServer.Client/BTCPayServerClient.StorePaymentMethods.cs:line 28
         at BTCPayApp.UI.Pages.Settings.WalletPage.GetStorePaymentMethod() in /Users/p/Downloads/Untitled/BTCPayApp.UI/Pages/Settings/WalletPage.razor:line 128
trce: LDK.lightning_background_processor[0]
      Rebroadcasting monitor's pending claims
trce: LDK.lightning_background_processor[0]
      Calling OnionMessageHandler's timer_tick_occurred

```
