### ISSUE TITLE
Pasting invite link doesn't work 

### ISSUE THREAD

**Issue by pavlenex** [btcpayserver/app#74]
To replicate:
1. Create an admin account and a store
2. Go to server settings users, and create user without password 
3. Copy the generated link in the app
4. See the error
```
s/p/Downloads/app/BTCPayApp.Server/bin/Debug/net8.0/BTCPayApp.Server
info: BTCPayApp.Core.AppDatabaseMigrator[0]
      Applying 2 migrations
info: BTCPayApp.Core.AppDatabaseMigrator[0]
      Migrations applied: 20240627110659_Init, 20240726135741_triggers
info: BTCPayApp.Core.Attempt2.OnChainWalletManager[0]
      Wallet state changed: WaitingForConnection
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7016
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5259
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /Users/p/Downloads/app/BTCPayApp.Server
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at BTCPayApp.UI.Components.QrScanModal.DisposeAsync() in /Users/p/Downloads/app/BTCPayApp.UI/Components/QrScanModal.razor:line 39
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'znwqImZBO2c66W3Ki8s22sNdvzMsqSjTJO6QUNpBhHk'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at BTCPayApp.UI.Components.QrScanModal.DisposeAsync() in /Users/p/Downloads/app/BTCPayApp.UI/Components/QrScanModal.razor:line 39
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at BTCPayApp.UI.Components.QrScanModal.DisposeAsync() in /Users/p/Downloads/app/BTCPayApp.UI/Components/QrScanModal.razor:line 39
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()
fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'sVaw441mj2golYQ8_fV2Oqe0iuik-8JgyFf0J6oqpwY'.
      Microsoft.JSInterop.JSDisconnectedException: JavaScript interop calls cannot be issued at this time. This is because the circuit has disconnected and is being disposed.
         at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson, JSCallResultType resultType, Int64 targetInstanceId)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, CancellationToken cancellationToken, Object[] args)
         at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
         at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
         at BTCPayApp.UI.Components.QrScanModal.DisposeAsync() in /Users/p/Downloads/app/BTCPayApp.UI/Components/QrScanModal.razor:line 39
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.<>c__DisplayClass85_0.<<Dispose>g__HandleAsyncExceptions|1>d.MoveNext()

```
<img width="842" alt="Screenshot 2024-07-29 at 23 44 49" src="https://github.com/user-attachments/assets/81fe9e4c-8658-4899-b959-3f1a3c9cc610">
<img width="792" alt="Screenshot 2024-07-29 at 23 44 54" src="https://github.com/user-attachments/assets/2408e3b0-5975-4b2e-847b-fc65a04d875f">

**Comment by dennisreimann** [comment]
This looks like a general connection error. Can you verify the server is up and running? For me it's working.

![grafik](https://github.com/user-attachments/assets/daf17394-e7c4-4e42-8a83-4b4a95ba33ee)

**Comment by pavlenex** [comment]
@dennisreimann How can I get back to that screen where I can paste invite link without nuking my entire database and starting from scratch? Is it even possible, it should be right?

**Comment by dennisreimann** [comment]
Good point, I added a link in 9ddf88db276082746b8b5a5982ea1e57504af757. Though you can also use the invite link on the login page, it would work too.

![grafik](https://github.com/user-attachments/assets/4072f474-9ce8-4e58-a4e3-f85e097517a2)

**Comment by dennisreimann** [comment]
Just checked: On the server we also require additional login after setting up the password. 

![grafik](https://github.com/user-attachments/assets/3b10612d-8c8f-4d2c-8979-0cfea4e9457f)

This is the same for all invitation cases: Store invitation and server invitation (with and without password set by the user who is inviting).

**Comment by pavlenex** [comment]
This now works for me. Thanks for fixing @dennisreimann
