### ISSUE TITLE
Setting Username causes bug

### ISSUE THREAD

**Issue by dstrukt** [btcpayserver/app#78]
Happening on current master. 

When attempting to change Name of account, I get this error:

<img width="1316" alt="Screen Shot 2024-08-08 at 11 47 25 AM" src="https://github.com/user-attachments/assets/8c13e6cf-7e81-40f5-a034-75b03a19ee53">

The log:

```
fail: PayServer:      BTC (Lightning): Error while contacting app
System.Threading.Channels.ChannelClosedException: The channel has been closed.
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at BTCPayServer.App.BTCPayAppLightningClient.Listener.WaitInvoice(CancellationToken cancellation) in /Users/andy/Documents/GitHub/app/submodules/btcpayserver/BTCPayServer/App/BTCPayAppLightningClient.cs:line 144
   at BTCPayServer.Payments.Lightning.LightningInstanceListener.Listen(CancellationToken cancellation) in /Users/andy/Documents/GitHub/app/submodules/btcpayserver/BTCPayServer/Payments/Lightning/LightningListener.cs:line 531
```

**Comment by dennisreimann** [comment]
I assume this is an UI issue not related to the channel closure. I'll take a look.

**Comment by pavlenex** [comment]
I had this exact problem today.
